# _config.yml - GitHub Pages configuration
source: .
destination: ./_site
plugins: []
markdown: kramdown
highlighter: rouge
theme: null

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
